spring:
  application:
    name: WashCarApi
  main:
    allow-bean-definition-overriding: true
server:
  port: 9001
ribbon:
  ReadTimeOut: 10000
  ConnectTimeOut: 10000
  MaxAutoRetris: 10  #重试次数
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  #注册中心的地址